services:
  web:
    build: .
    volumes:
      - ./app:/app/app
      - ./db:/app/db
      - ./manage.py:/app/manage.py
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/app/static
    ports:
      - "80:80"
    depends_on:
      - web